# Modelo de K-Vecinos Más Próximos (KNN)

MODELO DE VARIABLES CATEGORICAS (salvo edad y años consumiendo)

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

depresion = pd.read_csv("r_logistica.csv", sep=";")
#comprobamos que se ha cargado viendo los primeros registros
print(depresion.head())

   id  régimen  sexo  edad  edad_c  años  años_c  años_cat  tto  recuperación  \
0   1        3     1    18     -16     2     -12         1    0             0   
1   2        2     1    25      -9    10      -4         3    0             0   
2   3        3     1    26      -8    11      -3         3    0             0   
3   4        2     1    26      -8     8      -6         2    0             0   
4   5        2     1    28      -6    12      -2         3    0             1   

   recaída  
0        2  
1        2  
2        1  
3        2  
4        3  


In [6]:
#quitamos el id y el sexo (no interesan), edad_c, años_c, años_cat (redundantes)
depresion = depresion.drop(["id","sexo","edad_c","años_c","años_cat"], axis=1)

print(depresion.head())


   régimen  edad  años  tto  recuperación  recaída
0        3    18     2    0             0        2
1        2    25    10    0             0        2
2        3    26    11    0             0        1
3        2    26     8    0             0        2
4        2    28    12    0             1        3


In [7]:
#los vectores en el espacio serán solo las variables independientes
#Será la matriz X. Por eso se quita la variable criterio.

X = depresion.drop("recaída", axis=1)
X = X.values

#También en el vector y se colocan los valores de la variable a predecir (recaidas)
y = depresion["recaída"]
y = y.values

print(X)
print(y)

[[ 3 18  2  0  0]
 [ 2 25 10  0  0]
 [ 3 26 11  0  0]
 [ 2 26  8  0  0]
 [ 2 28 12  0  1]
 [ 3 29 11  0  0]
 [ 3 29 12  0  0]
 [ 3 30 12  0  0]
 [ 1 30 16  0  0]
 [ 1 30 15  0  0]
 [ 1 30 10  0  0]
 [ 1 31 16  0  0]
 [ 3 31 15  0  0]
 [ 2 31 13  0  1]
 [ 2 32 16  0  0]
 [ 3 32 11  0  0]
 [ 2 32 19  0  0]
 [ 3 32 15  0  1]
 [ 1 33 18  0  0]
 [ 2 33 16  0  0]
 [ 3 33 15  0  1]
 [ 2 33 18  0  0]
 [ 1 34 18  0  0]
 [ 1 34 18  0  0]
 [ 1 35 19  0  0]
 [ 1 35 15  0  0]
 [ 1 35 17  0  0]
 [ 2 35 12  0  0]
 [ 3 37 12  0  0]
 [ 1 37 19  0  1]
 [ 3 37  7  0  1]
 [ 1 38 22  0  0]
 [ 2 38 15  0  0]
 [ 1 39 18  0  0]
 [ 2 39 15  0  0]
 [ 1 40 22  0  1]
 [ 1 41 13  0  1]
 [ 3 42 11  0  0]
 [ 1 44 20  0  0]
 [ 2 47 20  0  1]
 [ 1 48 22  0  0]
 [ 1 49 21  0  0]
 [ 2 22  7  1  1]
 [ 2 23  6  1  1]
 [ 2 24  3  1  1]
 [ 3 25  9  1  1]
 [ 3 26 10  1  1]
 [ 1 27 10  1  0]
 [ 2 27 13  1  1]
 [ 2 27  7  1  1]
 [ 2 28  3  1  1]
 [ 1 28 10  1  1]
 [ 1 29 14  1  0]
 [ 2 29 10  1  1]
 [ 2 29  9  1  1]
 [ 2 31 10

In [8]:
#Se incluye un nuevo ejemplar del que se ha de estimar la recaída
new_data_point = np.array([
2,
21,
4,
1,
1
])

In [9]:
#se calculan las distancias entre el nuevo y todos los vectores de la matriz
#esto se hace calculando la norma a dichas restas

distances = np.linalg.norm(X-new_data_point, axis=1)  #distancia euclidea. La norma
print(distances)

#calculadas las distancias, se ha de coger un vecindario de 3
#para ello se ordenan las distancias y se toman los índices de las distancias más cortas

k = 3
nearest_neighbor_ids = distances.argsort()[:k]
print(nearest_neighbor_ids)

#ahora tomamos los valores en y de esos índices. y contiene los valores en "rings"
nearest_neighbor_rings = y[nearest_neighbor_ids]
print(nearest_neighbor_rings)

#la predicción será el promedio de los valores de "rings" de esos vecinos.
prediction = nearest_neighbor_rings.mean()
print(prediction)

[ 4.          7.34846923  8.77496439  6.55743852 10.67707825 10.77032961
 11.44552314 12.16552506 15.09966887 14.31782106 10.95445115 15.71623365
 14.96662955 13.49073756 16.34013464 13.15294644 18.65475811 15.62049935
 18.52025918 17.02938637 16.34013464 18.49324201 19.18332609 19.18332609
 20.59126028 17.88854382 19.18332609 16.18641406 17.97220076 21.97726098
 16.34013464 24.81934729 20.29778313 22.86919325 21.14237451 26.21068484
 21.97726098 22.20360331 28.0713377  30.5450487  32.49615362 32.80243893
  3.16227766  2.82842712  3.16227766  6.4807407   7.87400787  8.60232527
 10.81665383  6.70820393  7.07106781  9.2736185  12.88409873 10.
  9.43398113 11.70469991 14.89966443 14.2126704  15.         16.40121947
 17.74823935 15.26433752 19.26136028 18.05547009 17.49285568 20.
 16.79285562 23.38803113 19.74841766 23.47338919 21.67948339 24.24871131
 25.03996805 21.56385865 24.20743687 23.72762104 26.66458325 25.51470164
 24.18677324 28.23118843 30.38091506 30.09983389 34.02939905 35.874

Ha predicho que nuestro sujeto que se encuentra en el regimen 2 (externo), de 21 años, que lleva 4 años consumiendo, que recibe el tratamiento 1 (combinado) y que se ha recuperado no va a recaer

Vamos a ver que predicciones hace para distintos valores de K

In [10]:
from scipy.stats import mode

distances = np.linalg.norm(X-new_data_point, axis=1)  #distancia euclidea. La norma
print(distances)

results = []

for k in range(1, 11):
    nearest_neighbor_ids = distances.argsort()[:k]
    nearest_neighbor_rings = y[nearest_neighbor_ids]
    prediction = mode(nearest_neighbor_rings).mode[0]  # Usamos la moda para la predicción categórica
    
    # Agregar los resultados al listado
    results.append({
        'k': k,
        'nearest_neighbor_ids': nearest_neighbor_ids,
        'nearest_neighbor_rings': nearest_neighbor_rings,
        'prediction': prediction
    })

# Convertir el listado de resultados en un DataFrame
results_df = pd.DataFrame(results)

# Mostrar el DataFrame
print(results_df)


[ 4.          7.34846923  8.77496439  6.55743852 10.67707825 10.77032961
 11.44552314 12.16552506 15.09966887 14.31782106 10.95445115 15.71623365
 14.96662955 13.49073756 16.34013464 13.15294644 18.65475811 15.62049935
 18.52025918 17.02938637 16.34013464 18.49324201 19.18332609 19.18332609
 20.59126028 17.88854382 19.18332609 16.18641406 17.97220076 21.97726098
 16.34013464 24.81934729 20.29778313 22.86919325 21.14237451 26.21068484
 21.97726098 22.20360331 28.0713377  30.5450487  32.49615362 32.80243893
  3.16227766  2.82842712  3.16227766  6.4807407   7.87400787  8.60232527
 10.81665383  6.70820393  7.07106781  9.2736185  12.88409873 10.
  9.43398113 11.70469991 14.89966443 14.2126704  15.         16.40121947
 17.74823935 15.26433752 19.26136028 18.05547009 17.49285568 20.
 16.79285562 23.38803113 19.74841766 23.47338919 21.67948339 24.24871131
 25.03996805 21.56385865 24.20743687 23.72762104 26.66458325 25.51470164
 24.18677324 28.23118843 30.38091506 30.09983389 34.02939905 35.874

C:\Users\alici\AppData\Local\Temp\ipykernel_28576\3631891383.py:11: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  prediction = mode(nearest_neighbor_rings).mode[0]  # Usamos la moda para la predicción categórica


Vemos que con distintos valores de k, se sigue prediciendo que el nuevo sujeto no va a recaer. Esto indica que las características del sujeto son todas favorables a la recuperación, va a recuperarse sí o sí, y que por eso, nuestro modelo de KNN no encuentra divergencias varíando el valor de k.